net.Receive("AdminMenu", function(len, ply) 
    local staffname = net.ReadString()
    local targetname = net.ReadString()
    local DermaPanel = vgui.Create( "DFrame" )
    DermaPanel:SetSize( 300, 120 )
    DermaPanel:SetPos( 100, 100 )
    DermaPanel:SetTitle( "Give a warning to user: " .. targetname )
    DermaPanel:MakePopup()

    local TextEntry = vgui.Create( "DTextEntry", DermaPanel ) -- create the form as a child of frame
    TextEntry:SetPos( 25, 50 )
    TextEntry:SetSize( 175, 20 )
    TextEntry:SetText("Give a reason for the warning")
    TextEntry.OnEnter = function( self )
	    net.Start("sv_TargetWarningBegin")
        net.WriteString(targetname)
        net.WriteString(TextEntry:GetText())
        net.SendToServer()
        DermaPanel:Close()
    end

    local DermaButton = vgui.Create( "DButton", DermaPanel )
    DermaButton:SetText( "Warn player" )					
    DermaButton:SetPos( 22, 75 )					
    DermaButton:SetSize( 178, 25 )					
    DermaButton.DoClick = function()				
        net.Start("sv_TargetWarningBegin")
        net.WriteString(targetname)
        net.WriteString(TextEntry:GetText())
        net.SendToServer()	
        DermaPanel:Close()
    end
end)

net.Receive("SendMessage", function(len, ply) 
    local message = net.ReadString()
    chat.AddText(Color(255, 255, 255), message)
end)

net.Receive("TargetMenu", function(len, ply) 
    local staffmember = net.ReadString()
    local warnings = net.ReadString()
    local message = net.ReadString()
    local DermaPanel = vgui.Create( "DFrame" )
    DermaPanel:SetPos( 100, 100 )
    DermaPanel:SetSize( 300, 115 )
    DermaPanel:SetTitle( "Warning!" )
    DermaPanel:SetDraggable( true )
    DermaPanel:MakePopup()
    DermaPanel:ShowCloseButton(false)
    DermaPanel:SetDraggable(false)

    local staffnotification = vgui.Create("RichText", DermaPanel) -- This shows the staff member that is currently warning the user
    staffnotification:Dock(FILL)
    staffnotification:InsertColorChange(255, 0, 0, 255)
    staffnotification:AppendText("Warned by: " .. staffmember .. "\n")
    staffnotification:AppendText("Message: " .. message .. "\n")
    staffnotification:AppendText("Total warnings: " .. tonumber(warnings) .. "\n")
    local DermaButton = vgui.Create( "DButton", DermaPanel )
    DermaButton:SetText( "Acknowledge the warning" )				
    DermaButton:SetPos( 10, 75 )					
    DermaButton:SetSize( 250, 30 )					
    DermaButton.DoClick = function()				
        net.Start("WarningAccepted")
        net.WriteString(staffmember)
        net.WriteString(warnings)
        net.SendToServer()	
        chat.AddText(Color(255, 255, 255), "You have acknowledged the warning from staff member: " .. staffmember)
        DermaPanel:Close()
    end
end)